config/routes.rb
Rails.application.routes.draw do
 root to: 'stocks#index'
 devise_for :users
 resources :stocks do
   resources :mees,only: [:create, :destroy,:edit, :update,:show]
   resource :likes, only: [:create, :destroy]
   collection do
    get 'search'
  end
 end
 resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
belongs_to :user   # ユーザー/やってみたい → 1:多
belongs_to :stock   # 投稿/やってみたい    → 1:多

validates_uniqueness_of :stock_id, scope: :user_id 

end

app/models/mee.rb
class Mee < ApplicationRecord
  belongs_to :user
  belongs_to :stock
  validates :text, presence: true
  validates :published_at, presence: true
  # def self.search(search)
  #   if search != ""
  #     Mee.where('text LIKE(?))',"%#{search}%")
  #   else
  #     Mee.where('text LIKE(?)', "%c%")
  #   end
  # end
end

app/models/stock.rb
class Stock < ApplicationRecord
  
  validates :title, presence: true
  belongs_to :user
  has_many :likes,dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :mees, dependent: :destroy
  def self.search(search)
    if search != ""
      #.includes(:mees).whereでストックのなかに集約 ORで繋ぎmees.textを検索可能にした
      Stock.includes(:mees).where(['stocks.title LIKE(?) OR mees.text LIKE (?)' ,"%#{search}%", "%#{search}%"]).references(:mees)
    else
      Stock.where('title LIKE(?)', "%c%")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :stocks
         has_many :mees, dependent: :destroy
         has_many :likes, dependent: :destroy
         has_many :liked_stocks, through: :likes, source: :stock
         validates :name, presence: true
         def already_liked?(stock)
          self.likes.exists?(stock_id: stock.id)
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]  # 環境変数を読み込む記述に変更
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    like = current_user.likes.build(stock_id: params[:stock_id])
    if like.save
     redirect_back(fallback_location: root_path,notice: '「やってみたい👍」しました')
    else
      @stock = like.stock
      like = @stock.likes
      redirect_back(fallback_location: root_path,notice: 'すでに「やってみたい👍」してます')
    end
  end
  
  def destroy
    @user = current_user
    @stock = Stock.find(params[:stock_id])
    if like = Like.find_by(user_id: @user.id,stock_id:@stock.id)
     like.destroy
     redirect_back(fallback_location: root_path,notice: '「やってみたい👍」を解除しました')
    else
     redirect_back(fallback_location: root_path,notice: '「やってみたい👍」を押してください')
    end
  end
end

app/controllers/mees_controller.rb
class MeesController < ApplicationController
  # def index
  #   @mees = Mee.includes(:user)
  #   @stocks = Stock.includes(:user).order("created_at DESC")
  # end

  def new
    @stock = Stock.find(params[:stock_id])
    @mee = Mee.new
  end

  def create
    mee = Mee.create(mee_params)
   if mee.valid?
    
    redirect_to "/stocks/#{mee.stock.id}" ,notice: '✏️追加しました。'
  else
    redirect_to "/stocks/#{mee.stock.id}" ,notice: '記入してください。'
  end
   
  end
  def destroy
     stock = Stock.find(params[:stock_id])
     mee = stock.mees.find(params[:id])
    if current_user.id == mee.user.id
      mee.destroy
      redirect_to request.referer,notice: '⚠️削除しました'
    else
      render "stocks/show"
    end
  end
    def edit
      @stock = Stock.find(params[:stock_id])
      @mee   = @stock.mees.find(params[:id])
      unless user_signed_in?
        redirect_to root_path
      end
    end
    def update
      @stock = Stock.find(params[:stock_id])
      @mees   = @stock.mees.find(params[:id])
     if @mees.update(mee_params)
      redirect_to "/stocks/#{@stock.id}",notice: 'コメントを更新しました。'
      else
      render :edit
      end
    end
    def search
      # @stocks = Stock.search(params[:keyword])
      # @mees = Mee.search(params[:keyword])
    end
  

  private
  def mee_params
    params.require(:mee).permit(:text,:published_at).merge(user_id: current_user.id, stock_id: params[:stock_id])
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :authenticate_user!, except: [:index,:show]
  before_action :set_stock, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show, :search]

  
  def index
    @stocks = Stock.order("created_at DESC").includes(:user)
    @mees = Mee.order("published_at ASC").includes(:user)
    @all_ranks = Stock.find(Like.group(:stock_id).order('count(stock_id) desc').limit(3).pluck(:stock_id))

  end
  
  def new
    @stock = Stock.new
  end

  def create
    @stock = Stock.new(stock_params)
    if @stock.save
      redirect_to "/stocks/#{@stock.id}", notice: 'タイトルを作成しました🎉'
    else
      render :new
    end
  end

  def destroy    
    stock = Stock.find(params[:id])
  if  stock.destroy
    redirect_to root_path,notice: '削除しました。'
  else
    render :index
  end
  end
  def edit

  end
  
  def update
    stock = Stock.find(params[:id])
  if stock.update(stock_params)
    redirect_to request.referer, notice: '✅ タイトルを更新しました🎉'
  else
    redirect_to root_path
  end
  end
  
  def show

     @stock = Stock.find(params[:id])
     @mees = @stock.mees.order("published_at ASC").includes(:user)
     @mee = Mee.new
     like = @stock.likes
     

  end
  def search
    @stocks = Stock.search(params[:keyword])
    # @mees = Mee.search(params[:keyword])
  end



  private
  def stock_params
    params.require(:stock).permit(:title).merge(user_id: current_user.id)
  end
  
  def set_stock
    @stock = Stock.find(params[:id])
  end

  def move_to_index
    unless user_signed_in?
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @all_ranks = Stock.find(Like.group(:stock_id).order('count(stock_id) desc').limit(3).pluck(:stock_id))
  end

  
  
  def show
    
    @user = User.find(params[:id])
    @stocks = Stock.order("created_at DESC").includes(:user)
    @mees = Mee.order("published_at ASC").includes(:user)
    
    @likes = Like.includes(:user)
    @user_stocks = @user.stocks
    @likes_count = 0
       # countメソッドを使い、１つの投稿に結びつくイイねを予め定義しておいた@likes_countに足していく。
    @user_stocks.each do |stock|
      @likes_count += stock.likes.count
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mees_helper.rb
module MeesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stome</title>
  <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
      <link href="https://fonts.googleapis.com/css?family=Caveat rel="stylesheet">
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
            <%= stylesheet_link_tag 'application' %>
   <%= javascript_pack_tag 'application' %>
</head>

<body>
<header>
  <div class="logo">
    <h1>
      <span class="buruburu"><%= link_to "StoMee💡", root_path,class:"userList" %> </span>
    </h1>
  </div>
  <nav>
    <ul>
      <% if user_signed_in? %>
        <li>
        <%= link_to "マイページ", user_path(current_user), class: "btn btn-outline-info" %>
          <%= link_to "ログアウト", destroy_user_session_path, class: "btn btn-outline-info" ,method: :get, data: {confirm:"ログアウトしますか？"} %>
            <%= link_to "作成する", new_stock_path, class: "btn btn-outline-info" ,id: "submit"%>
        </li>
        <% else%>
          <li>
            <%= link_to "ログイン", new_user_session_path, class: "btn btn-outline-info" %>
              <%= link_to "新規登録", new_user_registration_path, class: "btn btn-outline-info" %>
          </li>
          <% end %>
    </ul>
  </nav>
</header>
<div class="wrapper">
<%= yield %>
  </div>
</body>
</html>

app/views/likes/_like.html.erb
<%# if@mees.length != 0 %>
<% if user_signed_in?  %>
     <% if current_user.already_liked?(stock) %>
<div id="comments_area">
          <div class="option" >
     <div class="report-btn">
       <p><span>やってみたい👍　</span><%=link_to stock.likes.count, stock_likes_path(stock), method: :delete,remote: true ,class:"button_like button_orange"%></p>
     </div>

     <%else%>
    <div class="option" >
     <div class="favorite-btn">
       <p> <span>やってみたい👍　</span><%=link_to stock.likes.count, stock_likes_path(stock), method: :post,remote: true ,class:"button_like button_pink"%></p>
     </div>
     <%end%>
     </div>
     <% else %>

     <% end %>
   </div>
   <%# end %> 
   </div>

app/views/likes/index.js.erb
$("#comments_area").html("<%= j(render 'likes/like', { likes: @likes }) %>")

app/views/mees/_new.html.erb
<ol class="sample1">
  <h3>ルーティン一覧</h3>
  <p>by
    <%= @stock.user.name %>
  </p>
  <%if  user_signed_in?%>
  <% @mees.each do |mees| %>
    <li> ⏰　
      　<%= l mees.published_at%>　→　
        <%= mees.text%>　
          <% if user_signed_in? && current_user.id == @stock.user_id %>
            <%= link_to '編集' ,edit_stock_mee_path(@stock,mees.id),method: :get %>　
              <%= link_to "削除",stock_mee_path(@stock,mees.id), method: :delete,data: {confirm:"本当に削除しますか？"}%>
                <% end %>
    </li>
    <% end %>
    <%else%>
    <%= render partial: "stocks/login" , locals: { stock: @stock }%>
    <% end %>
  
    

</ol>

app/views/mees/edit.html.erb
<%= form_with model: [@stock,@mee]  do |f| %>
  <%= f.time_select :published_at,{:minute_step => 5}%>
  <%= f.text_field :text %>
  <%= f.submit %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/stocks/_edit.html.erb
<div class="edit_t">
<%= form_with(model: @stock) do |f| %>
<%= f.text_field :title %>
<%= f.submit "タイトル更新" , id: "submit" ,data: {confirm:"タイトルを更新しますか？"} %>  
<% end %><%= button_to '削除' ,stock_path(@stock.id),method: :delete ,data: {confirm:"本当に削除しますか？"} %></div>

app/views/stocks/_login.html.erb
                                      <%= link_to "ログイン" , new_user_session_path %>　/　<%= link_to "新規登録" , new_user_registration_path %>
       <br><%= link_to "ユーザー登録" , new_user_registration_path%>をしたら「やってみたい👍」機能や<br>ルーティンを作成することができます

app/views/stocks/_rank.html.erb
 <% if user_signed_in?  %>
 <p>やってみたいランキング👑</p>
  <% @all_ranks.each.with_index(1)  do |stock ,i| %>
     <p>第<%= i %>位　　<%= "#{stock.user.name}"%>さん　</p>
     
 <p><%= link_to stock.title,stock_path(stock)  %>　👍総数<%= stock.likes.count %> </p>
 <%end%>
 <%else%>
 
  <p><%= link_to "ログイン" , new_user_session_path %>したらやってみたいランキングが見れます</p>
  <p>未登録の方はこちら→<%= link_to "新規登録" , new_user_registration_path %></p>
<br>
 <div id="side-b">
 <p>やってみたいランキング👑</p>

<p>第1位　　junさん　</p>

<p>朝活の流れ　👍総数2</p>

<p>第2位　　242424さん　</p>

<p>午後の読書　👍総数2

<p>第3位　　242424さん　</p>

<p>午後の読書????????　👍総数2</p>

<p>第4位　　junさん　</p>

<p>午後の読書　👍総数2</p>
</div>
 <%end%>

app/views/stocks/_stock.html.erb
<% @stocks.each do |stock| %>
  <div class="inline-block_test">
    <div class="inline">
    <%#=ここにアイコン%>
      <%#=span class="user"></span>
      <%#=ここにアイコン%>
      <%= link_to "#{stock.user.name}" ,user_path(stock.user.id) %>さんの投稿
        <% if user_signed_in? && current_user.id == stock.user_id %>
          <%= link_to '編集', stock_path(stock.id) %><br>
            <% else %>
              <%= link_to '詳細', stock_path(stock.id) %><br>
                <%end%> <br>
                  <h3>
                    <%= stock.title %>
                  </h3>
                  <% if user_signed_in?%>
        
                    <% if user_signed_in? && current_user.id == stock.user_id %>
 
                          <% end %>
                            <div class="index_m">
                              <% stock.mees.order(published_at: "ASC").each do |m|%>
                                <p> ⏰　<%= l m.published_at %>　〜　<%= m.text%><br>
                                
                                  
                                </p>
                                <%end%>

                                <%else%>
                                <%=render partial: "login" , locals: { stock: stock } %>


                                <%end%>
                            </div>
                            <%= render partial: "likes/like" , locals: { stock: stock }%>
    </div>
  </div>
  <%end%>
    <% if @stocks.length == 0 %>
      <div class="inline-block_test">
        <div class="inline">
          <p>じゅんいちさんの投稿<br>こちらはサンプルです</p>
          <h4>夕方ルーティン</h4>
          <p>⏰　18:00 ランニング</p>
          <p>⏰　18:20 シャワー</p>
          <p>⏰　18:30 夕食＆TV</p>
          <p>⏰　19:00 プログラミング学習</p>
          <p>⏰　20:00 ストレッチ＆マインドフルネス</p>
          <p>⏰　20:30 歯磨き</p>
          <p>⏰　20:50 寝かしつけ</p>
          <p>⏰　21:30 就寝</p>
        </div>
      </div>
      <% end %>
       

app/views/stocks/create.js.erb
// ERBタグを用いることでコントローラにて定義した@receiving_userの値を取得できます 
// また同様にERBタグを用いて部分テンプレートも適用できます(jを用いてエスケープ処理を行う必要あり)
$("#comments_area").html("<%= j(render partial: "likes/like" , locals: { stock: stock }) %>");
// いいね残高をコントローラにて定義した@sending_userを用いて表示します
$(".button_like button_pink").html("<%=link_to stock.likes.count, stock_likes_path(stock), method: :post,remote: true ,class:"button_like button_pink"%>")

app/views/stocks/index.html.erb
<link href="https://fonts.googleapis.com/earlyaccess/kokoro.css" rel="stylesheet"> <br>
<div id='hideMe'><%= notice %></div>
<h2 class="heading06" data-en="routine"><span class="buruburu">🎉 </span>最新ルーティン</h2>

<div class="search-form">
<%= form_with(url: search_stocks_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "タイトルを検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
</div>


  <div class='column--l'>
    <%= render partial: "stock" %>
  </div>
  <div class='column--r'>
    <div id="side-a">
      <%#= 部分テンプレート%>
        <%= render partial: "rank" %>
          <%#= 部分テンプレート%>
    </div>
  </div>
  

app/views/stocks/new.html.erb
<h2 class="heading06" data-en="routine"><span class="buruburu">✏️　</span>ルーティン作成</h2>
<ol class="sample1">
<h4><span class="buruburu">✅　</span>タイトルを入力してください</h4>
<br><%= render 'shared/error_messages', model: @stock %>   
   <%= form_with(model: @stock, local: true) do |f| %>
   <%= f.text_field :title, placeholder: "タイトル" %>
   <%#= f.text_field :"hoge", placeholder: "概要" %>
   <%= f.submit "ルーティン登録" %>
   <% end %></ol>

app/views/stocks/search.html.erb
<h2 class="heading06" data-en="routine"><span class="buruburu">🔎</span> ルーティン検索</h2>
<%= form_with(url: search_stocks_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "タイトルを検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>

<%= render partial: "stock" %>

app/views/stocks/show.html.erb
<br>
<div id="comments">
  <h2 class="heading06" data-en="routine"><span class="buruburu"><%= notice %></span></h2>
  <ol class="sample1">
    <h4><span class="buruburu">✨</span>
      <%= @stock.title %><span class="buruburu">✨</span></h4>
    <% if user_signed_in? && current_user.id == @stock.user_id %>
      <%= render partial: "edit" %><br>
        <%= render 'shared/error_messages', model: @mee %> 
        <span class="buruburu">⚠️ルーティンを入力してください</span>
          <%= form_with model: [@stock, @mee],  method: :post,id: "comment-form" do |f| %>
            <%= f.time_select :published_at,{:minute_step => 5}%>
              <%= f.text_field :text , class: "comment-text"%>
                <%= f.submit "ルーティンを追加", class: "comment-submit" %>
                  <% if @mees.length != 0 %>
                    <p style="text-align:right">
                      <%= link_to "投稿完了" ,root_path ,class:"btn btn-info" ,data: {confirm:"トップページへ移動します"}%>
                    </p>
                    <% end %>
                      <% end %>
                        <% end %>
                          <%= render partial: "likes/like" , locals: { stock: @stock }%>
  </ol>
  </p>
  <hr>
  <%= render partial: "mees/new" %>
    <%# 要素 終わり%>
      <% if @mees.length == 0 %>
        <ol class="sample1">
          <h5>⚠️⚠️こちらはサンプルです</h5>
          <li>(例)　⏰　7:00　 起床</li>
          <li>(例)　⏰　7:10　 洗顔</li>
          <li>(例)　⏰　7:20　 愛犬と散歩</li>
          <li>(例)　⏰　7:40　 朝食</li>
          <li>(例)　⏰　7:40　 Eテレを見る</li>
        </ol>
        <% end %>

app/views/stocks/stock_iine.js.erb
$('.index_ine').html(j("<%=link_to stock.likes.count, stock_likes_path(stock.id),remote: true, method: :post%>");

app/views/users/show.html.erb
<h2 class="heading06" data-en="routine">
      <%#=ここにアイコン%>
      <%#=span class="user"></span>
      <%#=ここにアイコン%>
<%= @user.name %>さんの投稿一覧</p>
</h2>
<%#=もし投稿がなければ%>
<%#= if @stocks.length != nil %>
<%#=もし投稿がなければ%>
  <div class="inline-block_test">
  <% @user.stocks.each do |stock| %>
    <div class="inline">
      <p><%= stock.title %>
      <%if user_signed_in? %>
     <% if user_signed_in? && current_user.id == stock.user_id %>
          <%= link_to '編集', stock_path(stock.id) %><br>
            <% else %>
              <%= link_to '詳細', stock_path(stock.id) %><br>
                <%end%>
          
        </p>
        <% stock.mees.order(published_at: "ASC").each do |m|%>
          <div class="comment">
            <p class="user-info"> </p>
            <p><%= l m.published_at%><%= m.text%></p>
          </div>
             <% end %>
             <%else%>
             <%=render partial: "stocks/login" , locals: { stock: stock } %>

             <% end %>
              <%#= 投稿ごとのやってみたい挿入予定%>
             <br><br>👍総数<%= stock.liked_users.count %>
             <%#= 投稿ごとのやってみたい挿入予定%>
    </div>
    <% end %>


     <div class='column--r'>
 <div id="side-c">
  <h4><%=@user.name%>がやってみたい👍している投稿</h4>
<% @user.liked_stocks.each do |stock| %>

  <p><%= link_to stock.title,stock_path(stock.id) %> <br>
  　👍総数 (<%= stock.liked_users.count %>)　By<%=link_to stock.user.name,user_path(stock.user.id)%></p>
 
<% end %>
</div></div>
  <%#= 自分のやってみたいした投稿表示 %>
   <div class='column--r'>
 <div id="side-a">
<%#= 部分テンプレート%>
👍総数　<%=@likes_count%>
 <%#= 部分テンプレート%>
 <%#=ユーザーランキング実装予定%>
 </div>  
</div>